function imgPart = expandCode(code, dict)
% Recursive helper function to decompress an image
% code: the code to be expanded to the effective values given by dict
% dict: the dictionary generated by compress()
% imgPart: the part of the image (as a row vector) that corresponds to the
% given code

if code > 255 % only codes above 255 need to be expanded, everything else is already the effective value of the image
    pos = code - 255;
    res1 = expandCode(dict(pos, 1), dict);
    res2 = expandCode(dict(pos, 2), dict);
    imgPart = [res1, res2];
else
    imgPart = code;
end

end

